### ISSUE TITLE
Suministros/Master proveedores

### ISSUE THREAD

**Issue by arkson** [arkson/herraven#1]
Tony este punto no lo tengo claro, por favor revísalo y me avisas:

- Cuando creas un proveedor existe una casilla para asociarlo con alguna materia prima, la idea de 

esto era una búsqueda inteligente, pero la verdad es que no sirve, eliminarlo y crear una función 

donde se pueda asociar al proveedor hasta cinco palabras claves.

**Comment by HerravenCardinale** [comment]
Hola, 

No puedo hacerte ver imágenes porque no tengo acceso a herraven.com

Lo que te puedo decir es que cuando creas a un proveedor puedes ver que hay una casilla 
donde seleccionas a que materia prima (previamente creada en otro modulo) asociar a este proveedor nuevo. La idea original era tener una relación/búsqueda inteligente al momento de identificar los proveedores, pero esto no funciona. 

Funciona que cuando crees a un nuevo proveedor tengas 5 palabras claves, algo similar al 
hashtag de IG o twitter, de forma de tener una búsqueda por palabras y de esa forma se filtren 
los proveedores.

**Comment by arkson** [comment]
Entendido, en estos momentos puedes acceder vía herrajesvenezolanos.com, herraven.com pronto estará disponible nuevamente, saludos
