### ISSUE TITLE
Fotos de los artículos

### ISSUE THREAD

**Issue by arkson** [arkson/herraven#1]
"Resolver porque las fotos de los artículos no se ven y no se pueden agrandar (las que no se ven)"

Por favor adjunta un print de pantalla de algún caso.
Saludos.

**Comment by MRTONYCARDINALE** [comment]
Cuando entras en ARTÍCULOS/MASTER ARTÍCULOS hay varios artículos cuyas fotos no se ven, adjunto imágenes: 

![1](https://cloud.githubusercontent.com/assets/16758663/12750459/a7815ccc-c989-11e5-8b20-718135bb7212.png)

![2](https://cloud.githubusercontent.com/assets/16758663/12750462/ad89a9f8-c989-11e5-9279-0702fd738163.png)
