### ISSUE TITLE
Almacén/Inventario/Consulta de Artículo - Mejora visual

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#106]
Esta es la mejora visual de la consulta del inventario de un artículo, a continuación los comentarios: 
1. Eliminar el botón de "Eliminar"
2. Eliminar "Números de cajas" y el número en sí. 
3. Eliminar los títulos "Artículo" y "Acabado", el contenido para ser título en si mismo. 
4. La disposición de la cantidad por caja y "Pz. por caja" cambia según diseño. 
5. Usar el formato de Materias Primas que venimos usando 
6. El formato de la fecha a usar es dd/mm/aa

Ver imágenes adjuntas para consulta: 

![consulta de cajas de producto terminado](https://cloud.githubusercontent.com/assets/16758663/18612879/fc1abf70-7d35-11e6-9a1a-34644de613a1.png)

![consulta de cajas](https://cloud.githubusercontent.com/assets/16758663/18612882/0bf87a18-7d36-11e6-9d7b-4e294028aa7f.png)

**Comment by MRTONYCARDINALE** [comment]
@arkson 

La consulta no está

**Comment by arkson** [comment]
@MRTONYCARDINALE en esta vista no habia ninguna consulta
