### ISSUE TITLE
Artículos tercerizados y Acabados

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#119]
Se me pasó comentar algo cuando desarrollamos los artículos tercerizados. 

Visto que los artículos tercerizados se van a entremezclar con los artículos de Master Artículos, 
tanto en el catalogo del cliente como en las listas de precios, creo prudente de que se le sea asociado
uno o más acabados. 

Ahora, esto no quiere decir que nos vamos a meter con cálculos de materias primas, sino se va a ser
innecesariamente complejo. 

Lo único que significa es que el % de venta va a ir asociado a la selección simple de uno o más acabados
existentes en tablas "Acabados", de forma que cada acabado tenga su precio tal como cualquier otro artículo y de forma que estos artículos tercerizados puedan aparecer en las listas de precios. 

Imágenes de referencia: 

![91a8e6f8-82b2-11e6-9d81-4d3492d91714](https://cloud.githubusercontent.com/assets/16758663/18896999/5d916a86-84f4-11e6-9561-36644393f259.png)

**Comment by MRTONYCARDINALE** [comment]
@arkson Me imagino que cuando actualizaste la plantilla de crear/editar artículos se dañaron varias cosas. Porque entré a probar esto y tambien tiene el mismo detalle que lo reportado en el issue anterior a este.

**Comment by arkson** [comment]
@MRTONYCARDINALE ya las correcciones están hechas
