### ISSUE TITLE
Lista de precios - Mejora visual 

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#128]
Al hacer doble clic sobre el ítem resaltado se abre. Resto de la explicación en la imagen

![listas de precios](https://cloud.githubusercontent.com/assets/16758663/18839599/910918e4-83d9-11e6-992d-8a881144a31a.png)

**Comment by arkson** [comment]
@MRTONYCARDINALE la función ver esta fallando, crea otro issue para solucionarlo.

Saludos.
Arcadio

**Comment by arkson** [comment]
@MRTONYCARDINALE donde queda el boton de "lista base"?, con esto realizo el siguiente issue

**Comment by MRTONYCARDINALE** [comment]
@arkson Esto está dañado, no está funcionando bien
