### ISSUE TITLE
Almacén/Inventario/Ver movimientos - Mejora Visual

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#143]
Una vez hecho el issue de mejora #142 Podemos dar la vista definitiva a Movimientos de Almacén. El formato es el mismo de siempre, con la única innovación de incluir un iconito para "Ingreso" y otro para "Egreso". 

![689](https://cloud.githubusercontent.com/assets/16758663/19059837/52f003d4-89b9-11e6-9fa3-0f16b6b208f8.png)

**Comment by arkson** [comment]
@MRTONYCARDINALE use otros íconos, si no te gustan y deseas los que pediste me avisas.

Saludos
