### ISSUE TITLE
Galvanica/Baños - Mejora visual

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#149]
La mejora visual de la vista de baños se va a hacer usando la plantilla de tablas que venimos usando. 

Notas: 
1. La lista de las materias primas asociadas se va a eliminar de la primera vista. 
2. Se van a asociar los valores de dos en dos para hacer tres bloques de parámetros (ver la imagen)
3. Los tres botones van a tenerse como iconos con su respectivo pop up. Como los iconos todavía no
los he mandado a hacer puedes dejar el cuadrito en blanco o poner un icono cualquiera mientras tanto. 
4. los pop ups son los siguientes para los tres botones que se van a pasar a icono: 
Botón Egresos -  Pop up "Materias Primas"
Botón Tiempo - Pop up "Tiempo de trabajo"
Botón Reporte - Pop up "Reporte"

![123](https://cloud.githubusercontent.com/assets/16758663/19098032/be929f7a-8a77-11e6-9e03-ab43810b9dcf.png)

![vista de galvanica banos](https://cloud.githubusercontent.com/assets/16758663/19098035/c771ef88-8a77-11e6-9664-7774176c09ce.png)

**Comment by MRTONYCARDINALE** [comment]
@arkson el botón de Tiempo no está funcionando bien. Y el botón de reporte está fallando:

Notice (8): Undefined variable: nombre [APP/View/Banos/reporte.ctp, line 35]

**Comment by arkson** [comment]
@MRTONYCARDINALE el reporte funciona pero no hay ninguna función desarrollada respecto al tiempo, puedes explicar a que se refiere dicha opción?

**Comment by MRTONYCARDINALE** [comment]
@arkson Originalmente, cuando desarrollamos este modulo de galvanica, había una función en la que podías introducir horas y minutos que se iban sumando a un total mensual y así... en este momento no recuerdo todos los específicos, pero el punto es que podías abrir un campo donde introducías horas y minutos y le dabas a agregar. Eso se sumaba y en el corte mensual tenias el total de horas y minutos. 

Eso estaba funcionando bien (tú lo desarrollaste) pero cuando saltamos a esta mejora visual el botón se daño y no accede.
