### ISSUE TITLE
Galvanica/Baño/Reporte - Mejora visual 

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#150]
Mejora visual de la presentación de Reporte de un baño en especifico

Notas: 
1. Al lado del título "Reporte Mensual" se incluye el baño en cuestión. Usando el mismo diseño 
   que tenemos en el sistema. 
2. Debajo del título se incluye el mes en cuestión usando el mismo formato de búsqueda para
   no alterar mucho el formato. "09-2016"
3. Si el reporte se hace sobre un mes en curso todavía, se incluye "(Mes en curso)" tal como se
   ve en la imagen. 

Resto de los detalles en la imagen. 

![84f0dc1c-83df-11e6-8590-1b0960b002a5](https://cloud.githubusercontent.com/assets/16758663/19098502/92e0b980-8a7b-11e6-979a-c3e19fc5e6ec.png)

![reporte de bano](https://cloud.githubusercontent.com/assets/16758663/19098690/6c3c0896-8a7d-11e6-8fdb-46624048e3be.png)

**Comment by arkson** [comment]
@MRTONYCARDINALE en el issue #149 lo coloque como un popup, eso fue lo que entendi, avisame si lo dejo en un popup y hago algunas modificaciones o lo desarrollo de este manera

**Comment by MRTONYCARDINALE** [comment]
@arkson Como pop up está bien, pero saca el resto de los detalles para cerrarlo. En las imágenes lo ves
