### ISSUE TITLE
CIO - Estadisticas mensuales - La pantalla se queda en blanco 

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#152]
CIO significa Centro de Información de la Organización. Es un modulo que aglutina graficas de las distintas estadisticas. Ya no recuerdo que estadisticas se graficaban allí. 

Fuese bueno arreglarlo y ver, para saber si hay que mejorar, ampliar o eliminar y volver a hacer. 

Visto que Herraven ya está listo es más facil tomar todos los datos para graficar estadisticas. 

Actualmente la vista mensual se queda en blanco, la mensual es la única que nos interesa. La semanal se mandó a eliminar en el issue #136 

![cio mensual](https://cloud.githubusercontent.com/assets/16758663/19099928/b5d8be58-8a88-11e6-87a3-3d85fc9c0050.png)

**Comment by arkson** [comment]
@MRTONYCARDINALE la vista se ve, pero esto no es un bug. Esta fallando la librería de los gráficos que usaron previamente llamada highcharts.js

Esto hay que reimplementarlo

**Comment by MRTONYCARDINALE** [comment]
@arkson Eso quiere decir que es mejor borrarlo todo y volverlo a hacer desde cero a repararlo?

**Comment by arkson** [comment]
@MRTONYCARDINALE por supuesto!

**Comment by MRTONYCARDINALE** [comment]
@arkson Vuelate entonces esas dos vainas y solo deja el nombre de CIO, en otro issue de desarrollo vemos que hacer de útil aquí. 

![123](https://cloud.githubusercontent.com/assets/16758663/19218849/899a3e14-8dd2-11e6-932e-d286ff5b36f2.png)
