### ISSUE TITLE
Estadísticas mensuales y semanales - Mejora de función 

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#159]
@arkson vi que pudiste recuperar estas funciones. Vamos a modificar algunas cosas para hacerlas más simples y a dejarlas funcionando. A continuación mi explicación: 
1. Vamos a eliminar los accesos "Estadísticas Mensuales" y "Estadísticas semanales" que pusiste arriba de "Clientes" y vamos a llevar el contenido de ambas a una sola vista que se acceda por "CIO"
2. "CIO" pasa a llamarse "Estadísticas" 
3. Las semanas están enumeradas "38, 39, 40...", vamos a cambiar la numeración por la siguiente 
   nomenclatura "WE 29/9, WE 6/10, WE 13/10..."

"WE" significa "week ending" y el formato de fecha corresponde a cada jueves de la semana. De hecho si mal no recuerdo la estadística debería cortar a las 23:59 horas de cada jueves, pero por algún motivo en vez de poner "WE fecha" se puso el número de la semana del año. No creo que sea tan complicado para ti suplantar el número por la fecha visto que ya tienes el patrón establecido. 
1. El acceso a gráficas que teníamos para cada estadística se va a eliminar, el sistema solo va a reportar los datos. Creo que fui muy ambicioso al tratar de pedir gráficas de una vez. Quizás en una versión más 
   avanzada de Herraven. 
2. El rango de semanas lo vamos a llevar de tres a seis. 
3. Las mejoras visuales se reportan en el siguiente issue. A continuación Imágenes de referencia: 

![123](https://cloud.githubusercontent.com/assets/16758663/19300344/c83140e4-9027-11e6-99d4-c56d47696e88.png)

**Comment by MRTONYCARDINALE** [comment]
@arkson Solo te faltó eliminar el duplicado, visto que ya tenemos Estadísticas

![123](https://cloud.githubusercontent.com/assets/16758663/22356213/f9511e06-e405-11e6-8164-b6e8aca399b5.png)

**Comment by arkson** [comment]
@MRTONYCARDINALE listo

**Comment by MRTONYCARDINALE** [comment]
@arkson Belleza!
