### ISSUE TITLE
Estadísticas mensuales y semanales - Mejora visual #159

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#160]
Siguiendo el issue #159 se presenta aquí la mejora visual definitiva de la función estadísticas. 

Lo único que me preocupa del diseño que presento es que la cantidad de digitos de la cifras vayan creciendo y se descuadre la presentación, sobre todo en las estadísticas semanales. No sé que puedas
ofrecerme para ese eventual caso. De resto, aquí están todos los detalles visuales a implementar: 

![311](https://cloud.githubusercontent.com/assets/16758663/19300864/974b32e8-902a-11e6-8ec2-8c84727b925f.png)

**Comment by arkson** [comment]
@MRTONYCARDINALE cuando el monto sea mayor a 1 millón te va a aparecer como "1,2M"
