### ISSUE TITLE
En Fundición/Moldes

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#18]
Visto que hay tantos moldes, debemos aplicar una categorización de dos niveles (Lineas y categorías)  tal como existe en Artículos y artículos de minuteria auxiliar.

**Comment by MRTONYCARDINALE** [comment]
@arkson Me comentaste por teléfono algo respecto a este issue. Sé que paginaste "1, 2, 3..." y el paginado si puede servir pero hay que hacer unos ajustes. 
Coméntame si se me está escapando algo y te respondo editando este issue para usar el paginado 
en vez del categorizado estilo "Min. auxiliar"

**Comment by arkson** [comment]
Este issue lo podríamos resolver con la paginación y me comentas que ajustes deberíamos hacer, con el categoizado implicaría bastante trabajo y modificaciones.

**Comment by MRTONYCARDINALE** [comment]
@arkson Si te refieres a "páginación" por la manera como está dispuesta la lista de clientes en Master clientes, entonces me parece bien. 

Esto también debe ser aplicable entonces a las ordenes de producción de Fundición

**Comment by arkson** [comment]
Perfecto, lo haré también en ordenes de producción.
