### ISSUE TITLE
En ARTÍCULOS/FORECAST:

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#2]
En artículos/forecast no se están filtrando los artículos ocultos, deben permanecer ocultos aquí. En el único lugar donde no deben permanecer ocultos es en Master Artículos visto que allí es donde se activan o se ocultan. 

![1](https://cloud.githubusercontent.com/assets/16758663/12750896/177653b4-c98c-11e5-8003-5305288a3b3b.png)

**Comment by arkson** [comment]
completado el requerimiento
