### ISSUE TITLE
Fundición/Moldes - mejorar vista

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#21]
Los específicos te los manda Rodney por correo 

![moldes](https://cloud.githubusercontent.com/assets/16758663/13078638/9421b65e-d492-11e5-95c8-8b1ffbd6a54b.jpg)

**Comment by arkson** [comment]
necesito los iconos para terminar la vista

**Comment by MRTONYCARDINALE** [comment]
@arkson Enviale un correo a Rodney que él te los envía, Rodney responde rápido a los emails. pixelaneos@outlook.com

**Comment by arkson** [comment]
ok, me comunicare con el

**Comment by MRTONYCARDINALE** [comment]
@arkson elimina la palabra "buscar" que viene luego de la casilla de busqueda y correr la casilla hacia la izquierda, tanto en moldes como en ordenes de producción 

![3](https://cloud.githubusercontent.com/assets/16758663/13474304/905dca9a-e08f-11e5-9220-bda4ad42e144.png)
