### ISSUE TITLE
Fundición/Ordenes de producción

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#22]
A continuación la mejora, los específicos te los manda Rodney por correo

![ordenes de produccion](https://cloud.githubusercontent.com/assets/16758663/13079155/00be3178-d495-11e5-9eba-fdbe0163752a.jpg)

**Comment by arkson** [comment]
necesito los iconos para terminar la vista

**Comment by MRTONYCARDINALE** [comment]
@arkson Ídem, pixelaneos@outlook.com

**Comment by MRTONYCARDINALE** [comment]
@arkson los iconitos no se están cargando ni en moldes ni en nueva orden de producción

![1](https://cloud.githubusercontent.com/assets/16758663/13474062/81282d96-e08e-11e5-8942-a5aff3171780.png)

![2](https://cloud.githubusercontent.com/assets/16758663/13474069/88be411c-e08e-11e5-91f9-2c4609e97dec.png)
