### ISSUE TITLE
Reorganización de funciones de Tablas 

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#25]
Visto que ahora tenemos más de una linea y categoría, vamos a aglutinar en una misma vista las funciones "Lineas" y "Categorías" visto que ambas forman parte de la segmentación de los artículos. La nueva función se va a llamar "Categorización Artículos"

La función de "Acabados" también la podemos poner dentro de esta vista ya que tiene que ver exclusivamente con los artículos. 

A continuación el flujo de acción reorganizado en imágenes: 

![1](https://cloud.githubusercontent.com/assets/16758663/13024968/c8d0fbc8-d1cf-11e5-8729-ecc931c6f000.png)

**Comment by MRTONYCARDINALE** [comment]
@arkson te fusilaste "Acabados" que lo eliminamos de "Tablas" para meterlo en la primera vista de "Categorización de artículos"

**Comment by arkson** [comment]
Listo!
