### ISSUE TITLE
Categorización Min. Auxiliar

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#26]
Siguiendo el mismo workflow del issue #25 reorganizar las lineas y categorías de Minuteria Auxiliar y llamar "Categorización Min. Auxiliar. 

Hacer lo mismo con las lineas y categorías de los moldes y llamar "Categorización Moldes" 

![2](https://cloud.githubusercontent.com/assets/16758663/13024998/6195ddba-d1d0-11e5-9cff-9325e8c5574f.png)

**Comment by arkson** [comment]
Tony que enlaces quieres tener en la "Categorización Moldes" ?
Por ejemplo: listados de moldes, órdenes de producción, nueva orden, etc

**Comment by arkson** [comment]
Reorganicé las lineas y categorías de Minuteria Auxiliar, como quisieras el cambio en el caso de los moldes.

Saludos
