### ISSUE TITLE
Amacén/Ingreso - Mejora de las vistas

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#28]
Vamos a mejorar la estética de estas vistas, adjunto imágenes de referencia para que veas como va 
a quedar. La diferencia más marcada es que en vez de una segunda pantalla para realizar el ingreso, vamos a tener un pop up. Los específicos te los pasa Rodney por correo

![almacen-ingreso](https://cloud.githubusercontent.com/assets/16758663/13078121/5d685ac6-d48f-11e5-86c4-ebaf5a4cb924.jpg)

![almacen-ingreso-a](https://cloud.githubusercontent.com/assets/16758663/13078134/64bf75d4-d48f-11e5-80c1-b9091dda253e.jpg)

**Comment by MRTONYCARDINALE** [comment]
@arkson Si bien la modificación fue hecha, se están dejando de lado detalles importantes de diseño. Recuerda que en estos issues de diseño, los detalles cuentan.

Respecto a la vista de los artículos, el marco no está ajustado, la interacción cuando pasas el cursor no existe y el botón verde no ha sido cambiado por el botón estandar azul según el diseño. 

Ocurre lo mismo con la vista del ingreso, si observas podrás denotar diferencias evidentes. 

--
Entiendo que hay un margen de diferencia entre lo que diseña Rodney y lo que tú montas, soy flexible con cierto margen pero aquí se está dejando bastante.

**Comment by arkson** [comment]
Por favor, pasame una imagen donde se refleje este punto: "Respecto a la vista de los artículos, el marco no está ajustado, la interacción cuando pasas el cursor no existe y el botón verde no ha sido cambiado por el botón estandar azul según el diseño."

No hay inconveniente en realizar los ajustes de diseño.
Saludos

**Comment by MRTONYCARDINALE** [comment]
@arkson comentado via Whatsapp con vídeo demostrativo
