### ISSUE TITLE
Suministros/Materias Primas

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#29]
Vamos a mejorar las vistas de materias primas según la fotografía adjunta. Los datos específicos del diseño los pasa Rodney por correo. 

Notas: 

1. El nombre "Inventario Materias prima" cambia a "Materia Prima" según el diseño 
2. Prestar atención a las mejoras en los detalles de las columnas, así como el tipo de alineación. 

Cualquier duda hazme saber

![materia-prima](https://cloud.githubusercontent.com/assets/16758663/13078566/1e382770-d492-11e5-9754-53a71b8db289.jpg)

**Comment by arkson** [comment]
Al tener los iconos vuelvo a subir la vista junto con algunos pequeños detalles.

Saludos

**Comment by MRTONYCARDINALE** [comment]
@arkson detalles a corregir: 

1. Los botones "Nuevo", "Movimientos" y "Reporte" no tienen el acabado final.
2. "Movimientos" y "Reportes" están pegados.
3. Cuando despliegas el menú del perfil, los botones de "Movimientos" y "Reportes" se mueven
4. Dar más espacio a las filas de las materias primas para que cuando pases el cursor por ellas
no vibre toda la vista sino que simplemente resalte en gris más oscuro la cursada.

5. Hubo una función que se altero: cada materia prima tiene su propia unidad (Kgs. Lts. Pz.) y 
dicha unidad se edita para cada una, es simplemente un campo. En la versión anterior, tenias 
una columna de "Unidad" donde se listaba la unidad de cada quien. Mientras que en el nuevo diseño, Rodney elimina dicha columna e incorpora las unidades a las cantidades. Por tanto 
la unidad se debe incorporar a las cantidades siguiendo el diseño planteado. Es por casualidad 
que todas las materias primas creadas ahora tienen Kg. como unidad, pero no se asume de hecho que todas las materias primas se manejan en kilos. 

6. Hacer el favor (a Rodney se le paso) de poner el título de la función en plural, o sea: "Materias Primas".

7. Me estoy dando cuenta que Rodney también se comió el año, favor colocar a la derecha del título "Materias Primas"

7. Dale margen izquierdo a la vista, el título y el margen están pegados a la izquierda.

**Comment by arkson** [comment]
Realizaré las modificaciones.
Saludos
