### ISSUE TITLE
Los catalogos en las sesiones de clientes

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#38]
Edité los catálogos que creaste "Catalogo 1, Catalogo 2, etc." le asocié distintas lineas de productos y luego me fui al Master Usuario a editar los usuarios con sesiones de clientes, de forma de tildar para algunos de ellos los distintos catálogos creados; de modo de probar la nueva función. 

Lo que ocurre es lo siguiente: 

1. La edición del usuario (los catálogos tildados) no se mantiene. Visto que no puedo ver los catálogos asociados en la vista porque no se ven, lo tengo que ver entrando a edición y ninguno se ve tildado. #36  

2. Cuando entro en la sesión del cliente luego de haber editado el usuario -tildando los distintos catálogos- me doy cuenta que a) la edición de los mismos no ha ocurrido (siguen llamándose "catalogo 1, Catalogo 2, etc.", b) que la discriminación de lineas/categorías de productos entre ellos no ha funcionado, c)Que las discriminación de los catalogos por los distintos usuarios tampoco ha funcionado. 

Una vez que esto esté reparado, podemos probar de nuevo todo el resto

**Comment by arkson** [comment]
Tony lo que esta ocurriendo es que los enlaces del menu están guardados estáticamente, por dicha razón, no cambia el nombre en el lado de los clientes, podemos hacer dos cosas:
- cambiar los nombres de catalago1, catalago2, etc por algunos que quieras
o
- implementar en un nuevo requerimiento que el submenu sea dinámico

**Comment by MRTONYCARDINALE** [comment]
@arkson opción 2: implementar en un nuevo requerimiento que el submenu sea dinámico

**Comment by arkson** [comment]
Ok, se realizará de esa manera, los catálogos ya se mantienen tildados

**Comment by MRTONYCARDINALE** [comment]
@arkson Veo que efectivamente la discriminación de catálogos en la sesión de clientes ya funciona. Lo que todavía no funciona (me imagino que se trabajará sobre ello) es lo dinámico de los nombres
