### ISSUE TITLE
Fundición/Moldes y Ordenes de producción

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#40]
Eliminar el "Buscar" antes de la casilla de búsqueda, visto que es redundante 

![1](https://cloud.githubusercontent.com/assets/16758663/14235702/ad3dbc84-f9cf-11e5-98d8-db94bad27302.png)

![2](https://cloud.githubusercontent.com/assets/16758663/14235723/f8e8a0a4-f9cf-11e5-97b1-0487c636e63f.png)

**Comment by MRTONYCARDINALE** [comment]
@arkson No veo esto, debo refrescar cache o algo así?

**Comment by arkson** [comment]
Refresca la cache del navegador
