### ISSUE TITLE
Fundición/Ordenes de producción: Pop up sobre los iconos

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#42]
Los pop up nunca se hicieron, deben hacerse para cerrar este ciclo. En la segunda imagen, el contenido de cada uno de los pop ups. 

![4](https://cloud.githubusercontent.com/assets/16758663/14235869/350d96a8-f9d4-11e5-8e78-ba7e1c158bbb.png)

![5](https://cloud.githubusercontent.com/assets/16758663/14235871/52e0a486-f9d4-11e5-9f6b-d6a687e9976e.png)

**Comment by arkson** [comment]
Tony no lo coloque en color amarillo, sino que use el que se usa por defecto en html, para colocarlo amarillo tendria q adaptar alguna funcionalidad adicional, cualquier cosa m avisas
