### ISSUE TITLE
En tablas

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#53]
En tablas creamos una nueva función llamada “Tab. Producción”, Dicha función es una tabla donde puedes listar nombres, asignarles un valor y una unidad. Similar a Materias primas con la diferencia que no se mueve inventarios, es una tabla estática editable.

**Comment by arkson** [comment]
@MRTONYCARDINALE no entiendo bien este punto, podrìas revisar nuevamente?

**Comment by MRTONYCARDINALE** [comment]
@arkson Crear una función, donde tengas tres campos, uno llamado "nombre" y puedas introducir un nombre, otro llamado "Valor" y puedas introducir un valor numérico (bsf.) y una tercera columna con un campo similar al primero pero llamado "Unidad". Es solo una tabla de tres columnas, y la ubicación es Tablas.
