### ISSUE TITLE
"Bonos de producción" - Nueva Función 

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#55]
Explicado a continuación: 

Tenemos también una nueva función llamada “Bonos de Producción” en Organización y después de cargar nómina. Dicha función es similar a la anterior con la diferencia que aquí no cargamos horas y minutos, sino que al escoger el empleado le podemos asociar tantos campos de “Tab. Producción” como queramos y luego ingresamos un número asociado a cada campo de forma similar a como se hace a la asociación de materias primas cuando creas un artículo. Es importante que cuando escojas un campo haga mención de su “valor” y su unidad. 
Luego que has asociado todos los empleados escogidos, tienes la vista general y haces clic en calcular, la cual emite un reporte con su pdf imprimible. Dicho reporte también se almacena en la función con el acceso a un botón de histórico. Todo siguiendo las lineas de diseño del nuevo Forecast.

**Comment by arkson** [comment]
@MRTONYCARDINALE campos de “Tab. Producción”  podrías explicarme cuales son, ya que no recuerdo, comprendo que quieres unos campos como materias primas donde eliges y al lado ingresas una cantidad, cuantos campos serían?

**Comment by arkson** [comment]
@MRTONYCARDINALE ya entendi esta asociado a la nueva funcion de tablas
