### ISSUE TITLE
Mejora visual de "Insumos" 

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#57]
Siguiendo la misma linea estética de insumos (para la entrada) y de Materias Primas para las listas, vamos a mejorar la presentación de los inventarios de insumos. Adjunto imagen de referencia.

Los únicos cambios respecto a Materias primas son: 
1. Los egresos de Insumos se hacen se forma manual, por tanto hay un icono más para ingresar los mismos.
2. Los insumos creados que no hayan tenido movimientos se pueden eliminar.

Estamos incluyendo en la entrada y en el encabezado el "Responsable" el cual es un simple campo que se llena en Tablas según #50 

![insumos 1](https://cloud.githubusercontent.com/assets/16758663/14681751/48ceff40-06ec-11e6-8d2f-45818896a07b.jpg)

![insumos 2](https://cloud.githubusercontent.com/assets/16758663/14681763/4fb2dc6e-06ec-11e6-8c2c-3ad05cc111f7.jpg)

**Comment by arkson** [comment]
@MRTONYCARDINALE el boton de movimientos actualmente es por registro, como deseas que lo manejemos en este caso? una vista general de movimientos?

**Comment by MRTONYCARDINALE** [comment]
@arkson El registro como funciona está bien por los momentos. quizás puedes poner un icono por cada ítem para llegar al movimiento directamente de cada uno. O pones el botón de movimientos en la barra de las herramientas donde al entrar filtras el ítem (entre los elementos de ese lote) y tienes acceso a movimientos tal cual está planteado en este momento.

Lo único que está mal respecto a movimientos en la versión anterior es que cuando haces clic en un "movimientos" en especifico igual luego debes filtrar.

**Comment by arkson** [comment]
@MRTONYCARDINALE colocare un icono por cada uno (si quieres uno en particular dime cual), y revisare que se filtren como debe ser
