### ISSUE TITLE
Capa estética de Clientes/Pedidos

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#58]
En las imágenes adjuntas están contenida la estética que aborda todos los elementos más no todas la combinación de situaciones posible. Lo cual no debería ser un problema para ti, visto que ya está programado. 

![1 pedidos](https://cloud.githubusercontent.com/assets/16758663/14874407/6068858a-0cc9-11e6-9992-ab4a13bb1bc9.jpg)

![1 pedidos 2](https://cloud.githubusercontent.com/assets/16758663/14874460/33f172b8-0cca-11e6-8200-b9a42535e571.jpg)

**Comment by arkson** [comment]
@MRTONYCARDINALE el boton de movimientos actualmente es por registro, como deseas que lo manejemos en este caso? una vista general de movimientos?

**Comment by arkson** [comment]
@MRTONYCARDINALE los filtros por estatus y acabados se encuentran programados, aunque deben tener el boton buscar para funcionar, lo agrgegamos a la vista?
