### ISSUE TITLE
Capa estética de Almacén/Egresos

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#59]
![2 egresos de almacen](https://cloud.githubusercontent.com/assets/16758663/14874565/a8b288de-0ccb-11e6-85bf-bab8075215dd.jpg)

![2 egresos-confirmar](https://cloud.githubusercontent.com/assets/16758663/14874570/b55d7440-0ccb-11e6-922c-fea0fcefa273.jpg)

![2 egresos-cajas](https://cloud.githubusercontent.com/assets/16758663/14874726/e3179194-0ccc-11e6-951f-d423cdbf13cc.jpg)

**Comment by arkson** [comment]
@MRTONYCARDINALE los filtros por estatus y acabados se encuentran programados, aunque deben tener el boton buscar para funcionar, lo agrgegamos a la vista?

**Comment by MRTONYCARDINALE** [comment]
@arkson O sea que no son como los clientes que conforme vas escribiendo vas filtrando? sino que debes escribir y pulsar "buscar" para que lo busque?

**Comment by arkson** [comment]
@MRTONYCARDINALE exactamente!
