### ISSUE TITLE
Catalogos y Lineas

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#61]
Hola, Veo que los catálogos ya se asocian bien en los clientes y esto está genial!

Ahora, debemos implementar una asociación faltante para que esto quede perfecto.
Fíjate que cuando entramos en Categorización Artículos/Catalogo lo único que puedes
hacer es crear catálogos, pero no puede asociarle Lineas de productos.

Entonces, la idea es que a cada catalogo se le puedan tildar las distintas lineas que cuando
abras el catalogo tengas acceso a dichas lineas y sus categorías. 

Eso es todo para terminar este asunto

**Comment by arkson** [comment]
@MRTONYCARDINALE debes acceder a categorización de artículos -> catálogos -> editar catalogo para usar la funcionalidad.
