### ISSUE TITLE
Linea del footer de la web

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#63]
Para no estar detrás de un programador que todos los años me actualice el año o el contenido del pie de página. Fuese bueno tener está linea editable en la función de "web" en cualquier lugarcito donde se pueda editar esto. 

![3](https://cloud.githubusercontent.com/assets/16758663/14934195/ed9384e6-0e72-11e6-95d8-99a4f83e5519.png)

©2016 Todos los derechos reservados Herrajes y accesorios Herraven S.A. RIf: J-30800588-6

**Comment by arkson** [comment]
@MRTONYCARDINALE debes acceder a Web -> Footer y encontraràs un botón llamado "Editar pie"
