### ISSUE TITLE
Galvanica - Baños

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#65]
Las horas/minutos no se están cargando en los distintos baños y aparentemente todos los baños tienen
la misma cantidad de horas

**Comment by arkson** [comment]
@MRTONYCARDINALE al entrar en galvanica/baños lo iconos que vez no son las horas y minutos son los demas parametros que se agregan en tablas/baños, en que sitio no se cargan o deberian mostrarse las Las horas/minutos?

**Comment by MRTONYCARDINALE** [comment]
Adjunto flujograma 

![3](https://cloud.githubusercontent.com/assets/16758663/17304024/7b0354d8-57f1-11e6-859e-1370184b1df5.png)

**Comment by MRTONYCARDINALE** [comment]
@arkson Ingresando tiempo (Cantidad de horas trabajadas) la vista se daña

![123](https://cloud.githubusercontent.com/assets/16758663/17647126/036afc5c-61b3-11e6-9819-18ee73e09203.png)
