### ISSUE TITLE
Suministros/Materias Primas

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#74]
Debe tener una categorización similar a la que tiene Insumos o Herramientas.

En tablas creamos una serie de categorías y luego las materias primas creadas se editan para que calcen dentro de alguna de las categorías. 

Esto es así porque me estoy dando cuenta que a la larga serán muchas materias primas y sino discriminados desde ahora, a la larga va a ser un chiquero. 

En el siguiente issue, explico como se van a crear las categorías de Materias primas en tablas  

Así como Insumos tiene la casita como icono y Herramientas tiene la llave inglesa, adjunto el dibujo icono de materias primas. Si necesitas la imagen con mejor resolución pídesela a Rodney. 

![icono materias primas](https://cloud.githubusercontent.com/assets/16758663/17154622/d0cd813c-534f-11e6-9c6c-b2a94d2d732d.png)

![88](https://cloud.githubusercontent.com/assets/16758663/17161971/b9f82432-537f-11e6-9095-8cbb508cd6dc.png)

**Comment by arkson** [comment]
@MRTONYCARDINALE cuales son las categorías de Materias primas que van en tablas?

**Comment by MRTONYCARDINALE** [comment]
@arkson la categorización de Materias Primas en Tablas va a funcionar igual que la de insumos o herramientas, es una copia de esa función para poder discriminar las distintas materias primas

**Comment by MRTONYCARDINALE** [comment]
@arkson Hola, la función está bien. Lo único que tengo que comentar es que las materias primas existentes de alguna manera cayeron en ciertas categorías y ahora no se como reagruparlas en donde 
se debe. Tengo miedo de eliminarlas visto que muchos artículos están creados con estas materias primas
asociadas y puedo generar problemas. 

Creo que lo que se puede hacer es, al editar la materia primas asignar en que categoría debe estar.

**Comment by MRTONYCARDINALE** [comment]
@arkson Comento esto porque tengo el temor de que se vaya a dañar la base de datos ya cargada, si puedes agregar la funcioncita para pasar las materias primas entre las categorías se resuelve esto. Cualquier otra solución hazme saber.
