### ISSUE TITLE
Artículos/Master Artículos - Mejora en la plantilla de crear un nuevo artículo 

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#77]
![1 1 vista de articulo](https://cloud.githubusercontent.com/assets/16758663/18899119/abeb416a-8504-11e6-948e-5ee731c5a829.jpg)

**Comment by MRTONYCARDINALE** [comment]
@arkson Hola entré a revisar ambos issues pero no están actualizados en mi navegador.

**Comment by arkson** [comment]
@MRTONYCARDINALE ya están actualizados los archivos

**Comment by MRTONYCARDINALE** [comment]
@arkson Esto no está funcionando bien, cuando le das a "+ Nuevo" se va a editar y se daña la vista. 

Adjunto imagen 

![123](https://cloud.githubusercontent.com/assets/16758663/22914246/ddcc40c2-f245-11e6-90da-fba48711b2ec.png)

**Comment by arkson** [comment]
@MRTONYCARDINALE Listo ya hice la corrección
