### ISSUE TITLE
En minuteria auxiliar: 

### ISSUE THREAD

**Issue by MRTONYCARDINALE** [arkson/herraven#9]
Cuando entras en Master artículos y te vas a una linea de producción, te jala las ordenes de producción y no el master artículos. Si entras en herraven.com y vas al master art. vas a ver la diferencia, a continuación imágenes: 

![2](https://cloud.githubusercontent.com/assets/16758663/12753404/2606cd84-c999-11e5-966d-44e13f98f44a.png)

![3](https://cloud.githubusercontent.com/assets/16758663/12753412/2c7ee21e-c999-11e5-9480-6fa5149f2e25.png)

**Comment by arkson** [comment]
completado el requerimiento
